version: "3.0"

services: 

  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    ports:
      - 8082:8080
      - 50000:50000
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports: 
      - 8081:8081

  tomcat:
    image: tomcat
    container_name: tomcat
    ports:
      - 8083:8080
    